version: '3'

services:
  silentpress:
    image: fritx/silentpress
    build:
      context: .
      args:
        # optional: if need a go-proxy
        # GOPROXY: https://goproxy.cn,direct
        GOPROXY: ''
    volumes:
      - ./.env:/app/.env
      - ./p:/app/p
      # optional: share go/pkg & speed up
      # - path/to/go/pkg:/go/pkg
    environment:
      HOST: '0.0.0.0' # for docker
    ports:
      - '127.0.0.1:8080:8080'
